### ISSUE TITLE
Dtls

### ISSUE THREAD

**Issue by gedw99** [simia-tech/netx#1]
Since you have QUIC, then its makes it sweeter to have DTLS ?

https://en.wikipedia.org/wiki/Datagram_Transport_Layer_Security
- note near the bottom how its really designed for RTC and QUIC.

https://github.com/pixelbender/go-dtls
- one imlementation semi working.

**Comment by phifty** [comment]
Seems like an interesting approach. But since `netx` does not implement quic itself, I might be better to issue this at underlying `quic` implementation (https://github.com/lucas-clemente/quic-go).

**Comment by gedw99** [comment]
of course makes sense. do yo want to raise it with that repo ?

**Comment by phifty** [comment]
I'd leave that to you, since I don't have time to follow up on this in the next days.

**Comment by gedw99** [comment]
ok cool. will ask him
